[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
base_mainnet = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_mainnet = { key = "${BASE_MAINNET_API_KEY}" }
base_sepolia = { key = "${BASE_SEPOLIA_API_KEY}" }